{
  "preserve_hierarchy": true,
  "files": [
    {
      "source": "/common/src/main/resources/assets/trafficengine/lang/en_us.json",
      "translation": "/common/src/main/resources/assets/trafficengine/lang/%locale_with_underscore%.json",
      "type": "json",
      "languages_mapping": {
        "locale_with_underscore": {
          "ar": "ar_sa",
          "bg": "bg_bg",
          "ca": "ca_es",
          "cs": "cs_cz",
          "da": "da_dk",
          "de": "de_de",
          "el": "el_gr",
          "en-GB": "en_gb",
          "es-ES": "es_es",
          "es-MX": "es_mx",
          "fi": "fi_fi",
          "fr": "fr_fr",
          "fr-CA": "fr_ca",
          "he": "he_il",
          "hu": "hu_hu",
          "id": "id_id",
          "it": "it_it",
          "ja": "ja_jp",
          "ko": "ko_kr",
          "nl": "nl_nl",
          "no": "no_no",
          "pl": "pl_pl",
          "pt-BR": "pt_br",
          "pt-PT": "pt_pt",
          "ro": "ro_ro",
          "ru": "ru_ru",
          "sk": "sk_sk",
          "sv-SE": "sv_se",
          "th": "th_th",
          "tr": "tr_tr",
          "uk": "uk_ua",
          "vi": "vi_vn",
          "zh-CN": "zh_cn",
          "zh-TW": "zh_tw"
        }
      }
    }
  ],
  "pull_request_title": "Update Traffic Engine translations"
}
