# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Mod properties
mod_version = 1.1
mod_id = trafficengine
maven_group = com.destan.trafficengine
archives_name = trafficengine
enabled_platforms = fabric,forge

# Mod Info
display_name = Traffic Engine
authors = Destan
description = A comprehensive traffic and road management mod bringing advanced traffic lights, asfalt variants and traffic signs to your modern cities.
modpage = https://www.curseforge.com/minecraft/mc-mods/trafficengine
license = GNU General Public License v3.0
icon = mod_icon.png
java_version = 17
datapack_version = 9

# Minecraft properties
minecraft_version = 1.20.1
parchment_version = 2023.09.03
next_unsupported_minecraft_version=1.20.2

## Modloader
fabric_loader_version = 0.15.11
fabric_api_version = 0.90.4+1.20.1
forge_version = 1.20.1-47.2.1
forge_loader_version = 47
forge_dependency_version = 47

## Base Dependencies
architectury_api_version = 9.2.14
mixin_extras_version = 0.5.3
dragonlib_version = beta-3.0.21
forge_config_api_port_version = 8.0.0
modmenu_version = 7.2.2

# Dependencies
jei_version = 15.20.0.106

